#!/bin/bash

#This is a script made my the great Andrew Kuntz, because Jon Ferriter doesn't know how to use API calls

user="userHere"
password="passHere"
url="https://xxxx.jamfcloud.com"
prestageID="idHere"

# Get username and password encoded in base64 format and stored as a variable in a script:
encodedCredentials=$( printf "$user:$password" | /usr/bin/iconv -t ISO-8859-1 | /usr/bin/base64 -i - )

# Use encoded username and password to request a token with an API call and store the output as a variable in a script:
token=$(/usr/bin/curl $url/uapi/auth/tokens -s -X POST -H "Authorization: Basic $encodedCredentials" | grep token | awk '{print $3}' | tr -d ',"')

echo $token

curl -X 'GET' \
$url/api/v2/computer-prestages/$prestageID/scope \
-H 'accept: application/json' \
-H "Authorization: Bearer $token" > /users/Shared/ComputerPrestageScoping.json
